### ISSUE TITLE
Error on dart tools/screenshots.dart command

### ISSUE THREAD

**Issue by lhimo** [tim-smart/flutter-emulators-screenshots-demo#4]
Cloning the repo and giving the command `dart tools/screenshots.dart` gives the following error on the latest `stable` flutter version:

```
Unhandled exception:
type 'None<dynamic>' is not a subtype of type 'FutureOr<Option<String>>'
#0      _FutureListener.handleError (dart:async/future_impl.dart:172:20)
#1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:719:47)
#2      Future._propagateToListeners (dart:async/future_impl.dart:740:24)
#3      Future._completeError (dart:async/future_impl.dart:550:5)
#4      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:606:7)
#5      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#6      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#7      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#8      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:402:11)
#9      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

Both `flutter doctor` and `flutter pub get` were run before with no issues. The latest `dev` flutter branch gives a similar error:

```
Unhandled exception:
Invalid argument(s) (onError): The error handler of Future.then must return a value of the returned future's type
#0      _FutureListener.handleError (dart:async/future_impl.dart:188:9)
#1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:779:47)
#2      Future._propagateToListeners (dart:async/future_impl.dart:800:13)
#3      Future._completeError (dart:async/future_impl.dart:610:5)
#4      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:666:7)
#5      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#6      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#7      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#8      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:402:11)
#9      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

```

**Comment by memoriasIT** [comment]
As of today I am also getting an error there:

fvm: running Dart from Flutter "3.3.8"

Unhandled exception:
DeviceError.flutterFailure(op: shutdownAll, error: FlutterError.toolchainFailure(op: running, message: ProcessException: Not a directory
  Command: flutter devices))
#0      unwrap.<anonymous closure> (package:fpdt/either.dart:21:14)
#1      Left._fold (package:fpdt/either.dart:459:13)
#2      unwrap (package:fpdt/either.dart:20:50)
<asynchronous suspension>
#3      main (file:///Users/me/Downloads/flutter-emulators-screenshots-demo-main/tools/screenshots.dart:10:3)
<asynchronous suspension>
